# Generated by Django 5.0.3 on 2025-03-15 23:33

import core.models.definitions.DateTimeWithoutTZ
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='registered_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistverification',
            name='approved_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artistverification',
            name='requested_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='deleted_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='detected_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(editable=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_at',
            field=core.models.definitions.DateTimeWithoutTZ.DateTimeWithoutTZField(auto_now=True),
        ),
    ]
