# Generated by Django 5.0.3 on 2025-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_artist_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
