# Generated by Django 5.0.3 on 2025-03-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gallery_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
