# Generated by Django 5.0.3 on 2025-03-15 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_cover_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
