# Generated by Django 5.0.3 on 2025-03-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gallery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
