# Generated by Django 5.0.3 on 2025-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_gallery_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
