# Generated by Django 5.0.3 on 2025-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover_photo_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
