# Generated by Django 5.0.3 on 2025-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_artist_instagram_url_alter_artist_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
